territory: fr
weekend:
    - saturday
    - sunday

public_holidays:
    - jour de l'an':
        years: all
        month: 1
        day: 1
        carry_forward: false
    - fête du travail:
        years: all
        month: 5
        day: 1
        carry_forward: false
    - fin de la 2ème guerre mondiale
        years: all
        month: 5
        day: 8
        carry_forward: false
    - lundi de Pâques:
        years: all
        class_method: ReligiousFestival.easter
        carry_forward: false
    - jeudi de l'Ascension:
        years: all
        class_method: ReligiousFestival.ascension_day
        carry_forward: false
    - fête nationale:
        years: all
        month: 7
        day: 14
        carry_forward: false
    - assomption:
        years: all
        month: 8
        day: 15
        carry_forward: false
    - Toussaint:
        years: all
        month: 11
        day: 1
        carry_forward: false
    - armistice:
        years: all
        month: 11
        day: 11
        carry_forward: false
    - Noël:
        years: all
        month: 12
        day: 25
        carry_forward: true
 