territory: fr

weekend:
    - saturday
    - sunday

public_holidays:
    Jour de l'An:
        years: all
        month: 1
        day: 1
        

    Fête du Travail:
        years: all
        month: 5
        day: 1
        

    Fête de la Victoire 1945:
        years: all
        month: 5
        day: 8
        

    Lundi de Pâques:
        years: all
        class_method: ReligiousFestival.easter_monday
        

    Ascension catholique:
        years: all
        class_method: ReligiousFestival.ascension_day
        
        
    Lundi de Pentecôte:
        years: all
        class_method: ReligiousFestival.whit_monday
        

    Fête nationale:
        years: all
        month: 7
        day: 14
        

    Assomption:
        years: all
        month: 8
        day: 15
        

    Toussaint:
        years: all
        month: 11
        day: 1
        
 
    Armistice:
        years: all
        month: 11
        day: 11
        
 
    Noel:
        years: all
        month: 12
        day: 25
        take_after:
            - Saturday
            - Sunday
 
