territory: fr

weekend:
    - saturday
    - sunday

public_holidays:
    Jour de l'An:
        years: all
        month: 1
        day: 1
        carry_forward: false

    Fête du Travail:
        years: all
        month: 5
        day: 1
        carry_forward: false

    Fête de la Victoire 1945:
        years: all
        month: 5
        day: 8
        carry_forward: false

    lundi de Pâques:
        years: all
        class_method: ReligiousFestival.easter_monday
        carry_forward: false

    Ascension catholique:
        years: all
        class_method: ReligiousFestival.ascension_day
        carry_forward: false
        
    Lundi de Pentecôte:
        years: all
        class_method: ReligiousFestival.whit_monday
        carry_forward: false

    Fête nationale:
        years: all
        month: 7
        day: 14
        carry_forward: false

    Assomption:
        years: all
        month: 8
        day: 15
        carry_forward: false

    Toussaint:
        years: all
        month: 11
        day: 1
        carry_forward: false
 
    Armistice:
        years: all
        month: 11
        day: 11
        carry_forward: false
 
    Noel:
        years: all
        month: 12
        day: 25
        carry_forward: true
 