territory: us
weekend:
    - saturday
    - sunday

public_holidays:
    New Year's Day:
        years: all
        month: 1
        day: 1
        carry_forward: true
    Birthday of Martin Luther King, Jr.:
        years: all
        month: 1
        day: 19
        carry_forward: false
    Washington's Birthday:
        years: all
        month: 2
        day: third_monday
    Memorial Day:
        years: all
        month: 5
        day: last_monday
    Independence Day:
        years: all
        month: 7
        day: 4
        sunday_to_monday: true
        saturday_to_friday: true
    Labor Day:
        years: all
        month: 9
        day: first_monday
    Columbus Day:
        years: all
        month: 10
        day: second_monday
    Veterans' Day:
        years: all
        month: 11
        day: 11
        sunday_to_monday: true
        saturday_to_friday: true
    Thanksgiving Day:
        years: all
        month: 11
        day: fourth_thursday
    Christmas Day:
        years: all
        month: 12
        day: 25
        sunday_to_monday: true
        saturday_to_friday: true
